// ============================================
// PRODUCTS DATABASE - PRIMO NUTRITION ONLY
// ============================================

const productsDB = [
    {
        id: 1,
        nameFr: "PrimoShake Protéine Vanille",
        nameAr: "بروتين بريموشيك فانيليا",
        price: 599,
        oldPrice: 699,
        category: "proteines",
        icon: "fa-blender",
        image: "images/products/primoshake-vanille.jpg",
        badge: "promo",
        rating: 4.9,
        stock: 50,
        description: "Shake protéiné Primo - Haute digestibilité, goût vanille - 2kg"
    },
    {
        id: 2,
        nameFr: "PrimoShake Protéine Chocolat",
        nameAr: "بروتين بريموشيك شوكولاتة",
        price: 599,
        oldPrice: 699,
        category: "proteines",
        icon: "fa-blender",
        image: "images/products/primoshake-chocolat.jpg",
        badge: "promo",
        rating: 4.9,
        stock: 45,
        description: "Shake protéiné Primo - Goût chocolat intense - 2kg"
    },
    {
        id: 3,
        nameFr: "PrimoShake Protéine Fraise",
        nameAr: "بروتين بريموشيك فراولة",
        price: 599,
        oldPrice: 699,
        category: "proteines",
        icon: "fa-blender",
        image: "images/products/primoshake-fraise.jpg",
        badge: null,
        rating: 4.8,
        stock: 40,
        description: "Shake protéiné Primo - Goût fraise naturel - 2kg"
    },
    {
        id: 4,
        nameFr: "Primopeanut Beurre de Cacahuète",
        nameAr: "زبدة الفول السوداني بريموبينوت",
        price: 149,
        oldPrice: 189,
        category: "beurres",
        icon: "fa-jar",
        image: "images/products/primopeanut.jpg",
        badge: "promo",
        rating: 4.8,
        stock: 80,
        description: "Beurre de cacahuète Primo - 100% naturel, riche en protéines - 500g"
    },
    {
        id: 5,
        nameFr: "Primopeanut Crunchy",
        nameAr: "بريموبينوت كرانتشي",
        price: 159,
        oldPrice: 199,
        category: "beurres",
        icon: "fa-jar",
        image: "images/products/primopeanut-crunchy.jpg",
        badge: "new",
        rating: 4.7,
        stock: 65,
        description: "Beurre de cacahuète Primo croustillant - 500g"
    },
    {
        id: 6,
        nameFr: "Primopeanut Chocolat",
        nameAr: "بريموبينوت شوكولاتة",
        price: 169,
        oldPrice: 209,
        category: "beurres",
        icon: "fa-jar",
        image: "images/products/primopeanut-chocolat.jpg",
        badge: "promo",
        rating: 4.9,
        stock: 55,
        description: "Beurre de cacahuète Primo au chocolat - 500g"
    },
    {
        id: 7,
        nameFr: "Primo Mass Gainer Chocolat",
        nameAr: "بريمو ماس جينر شوكولاتة",
        price: 849,
        oldPrice: 999,
        category: "gainers",
        icon: "fa-weight-scale",
        image: "images/products/primo-mass-chocolat.jpg",
        badge: "promo",
        rating: 4.7,
        stock: 30,
        description: "Gainer Primo pour prise de masse - 3kg chocolat"
    },
    {
        id: 8,
        nameFr: "Primo Mass Gainer Vanille",
        nameAr: "بريمو ماس جينر فانيليا",
        price: 849,
        oldPrice: 999,
        category: "gainers",
        icon: "fa-weight-scale",
        image: "images/products/primo-mass-vanille.jpg",
        badge: null,
        rating: 4.6,
        stock: 25,
        description: "Gainer Primo pour prise de masse - 3kg vanille"
    },
    {
        id: 9,
        nameFr: "Primo Pre-Workout Energy",
        nameAr: "بريمو بري ورك آوت إنرجي",
        price: 349,
        oldPrice: 399,
        category: "preworkout",
        icon: "fa-bolt",
        image: "images/products/primo-preworkout.jpg",
        badge: "new",
        rating: 4.8,
        stock: 40,
        description: "Pré-entraînement Primo - Énergie explosive et concentration - 300g"
    },
    {
        id: 10,
        nameFr: "Primo BCAA 2:1:1",
        nameAr: "بريمو بي سي إيه إيه 2:1:1",
        price: 299,
        oldPrice: 399,
        category: "recuperation",
        icon: "fa-prescription-bottle",
        image: "images/products/primo-bcaa.jpg",
        badge: "promo",
        rating: 4.7,
        stock: 35,
        description: "Acides aminés branchés Primo pour récupération - 300g"
    },
    {
        id: 11,
        nameFr: "Primo Creatine Monohydrate",
        nameAr: "بريمو كرياتين مونوهيدرات",
        price: 249,
        oldPrice: 299,
        category: "recuperation",
        icon: "fa-capsules",
        image: "images/products/primo-creatine.jpg",
        badge: "promo",
        rating: 4.8,
        stock: 45,
        description: "Créatine pure Primo - 300g, force et puissance"
    },
    {
        id: 12,
        nameFr: "Primo Glutamine",
        nameAr: "بريمو جلوتامين",
        price: 229,
        oldPrice: 279,
        category: "recuperation",
        icon: "fa-capsules",
        image: "images/products/primo-glutamine.jpg",
        badge: null,
        rating: 4.6,
        stock: 40,
        description: "L-Glutamine Primo - Récupération musculaire - 300g"
    },
    {
        id: 13,
        nameFr: "Primo Omega 3",
        nameAr: "بريمو أوميغا 3",
        price: 179,
        oldPrice: 219,
        category: "sante",
        icon: "fa-heart-pulse",
        image: "images/products/primo-omega3.jpg",
        badge: "promo",
        rating: 4.7,
        stock: 60,
        description: "Oméga 3 Primo - Santé cardiovasculaire - 120 capsules"
    },
    {
        id: 14,
        nameFr: "Primo Multivitamines",
        nameAr: "بريمو مالتي فيتامين",
        price: 199,
        oldPrice: 249,
        category: "sante",
        icon: "fa-tablets",
        image: "images/products/primo-multivitamines.jpg",
        badge: "new",
        rating: 4.8,
        stock: 55,
        description: "Multivitamines Primo - 60 comprimés, énergie quotidienne"
    },
    {
        id: 15,
        nameFr: "Primo Fat Burner",
        nameAr: "بريمو حارق الدهون",
        price: 289,
        oldPrice: 349,
        category: "minceur",
        icon: "fa-fire",
        image: "images/products/primo-fatburner.jpg",
        badge: "promo",
        rating: 4.6,
        stock: 40,
        description: "Brûleur de graisses Primo - Thermogénique - 90 capsules"
    },
    {
        id: 16,
        nameFr: "Primo L-Carnitine",
        nameAr: "بريمو إل كارنتين",
        price: 259,
        oldPrice: 319,
        category: "minceur",
        icon: "fa-fire-flame-curved",
        image: "images/products/primo-carnitine.jpg",
        badge: "promo",
        rating: 4.7,
        stock: 45,
        description: "L-Carnitine Primo - Aide à la perte de poids - 500ml"
    },
    {
        id: 17,
        nameFr: "Primo Shaker Pro",
        nameAr: "بريمو شاكر برو",
        price: 79,
        oldPrice: 99,
        category: "accessoires",
        icon: "fa-blender",
        image: "images/products/primo-shaker.jpg",
        badge: "promo",
        rating: 4.9,
        stock: 100,
        description: "Shaker Primo - 700ml, avec compartiment à poudre"
    },
    {
        id: 18,
        nameFr: "Primo Gourde Sport",
        nameAr: "بريمو قارورة رياضية",
        price: 99,
        oldPrice: null,
        category: "accessoires",
        icon: "fa-bottle-water",
        image: "images/products/primo-gourde.jpg",
        badge: "new",
        rating: 4.8,
        stock: 80,
        description: "Gourde Primo - 1L, sans BPA, avec marquages heures"
    }
];

// Categories - Primo only
const categoriesDB = [
    { id: "proteines", icon: "fa-blender", labelFr: "Protéines", labelAr: "البروتينات" },
    { id: "beurres", icon: "fa-jar", labelFr: "Beurres de Cacahuète", labelAr: "زبدة الفول السوداني" },
    { id: "gainers", icon: "fa-weight-scale", labelFr: "Gainers", labelAr: "مكملات زيادة الوزن" },
    { id: "preworkout", icon: "fa-bolt", labelFr: "Pre-Workout", labelAr: "ما قبل التمرين" },
    { id: "recuperation", icon: "fa-capsules", labelFr: "Récupération", labelAr: "الاستشفاء" },
    { id: "sante", icon: "fa-heart-pulse", labelFr: "Santé", labelAr: "الصحة" },
    { id: "minceur", icon: "fa-fire", labelFr: "Minceur", labelAr: "التخسيس" },
    { id: "accessoires", icon: "fa-bottle-water", labelFr: "Accessoires", labelAr: "الملحقات" }
];

window.productsDB = productsDB;
window.categoriesDB = categoriesDB;